Components/SidebarItemViewComponent/SidebarItemViewComponent.cs
using velocitor_helpdesk_asp.Models;
using Microsoft.AspNetCore.Mvc;

namespace velocitor_helpdesk_asp.Components
{
    public class SidebarItemViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(
            string linkText,
            string iconClass,
            string aspArea,
            string aspController,
            string aspAction
        )
        {
            var model = new SidebarItemModel
            {
                LinkText = linkText,
                IconClass = iconClass,
                AspArea = aspArea,
                AspController = aspController,
                AspAction = aspAction
            };
            return View(model); // Pass the model to the view
        }
    }
}

Views/Shared/_HeaderPartial.cshtml
<header class="flex items-center w-full h-[4.125rem] bg-white px-4 shadow border-b border-b-slate-200">
    <div class="justify-start w-1/2">
        <label htmlFor="sidebar-toggle" for="sidebar-toggle" class="cursor-pointer">
            <i class="fa-solid fa-chevrons-right fa-1x text-veldarkgray transition-transform duration-300 ease-in-out"></i>
        </label>
    </div>
    <div class="flex shrink-0 justify-center">
        <a asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/images/VTrack-Logo-Large.png" alt="Velocitor Solutions" class="h-12" />
        </a>
    </div>
    <div class="flex justify-end w-1/2">
        <partial name="_LoginPartial" />
    </div>
</header>

Views/Shared/_Layout.cshtml
@{
    var requiresAuth = ViewData["RequiresAuth"] as bool?; // Safely cast to nullable bool
    var userIsAuthenticated = User?.Identity?.IsAuthenticated ?? false;

    if (requiresAuth.HasValue && requiresAuth.Value && !userIsAuthenticated)
    {
        Layout = null; // If user needs to be logged in but isn't, set no layout.
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - velocitor_helpdesk_asp</title>
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/8e4196e614.js" crossorigin="anonymous"></script>
</head>
    <body>
        <div class="flex min-h-screen">
            <input type="checkbox" id="sidebar-toggle" name="sidebar-toggle" class="hidden" />
            <partial name="_SidebarPartial" />
            <div class="flex flex-col grow min-w-0">
                <partial name="_HeaderPartial" />
                <div class="flex flex-1 bg-slate-200 p-4">
                    <main role="main" class="max-h-[calc(100vh-8rem)] flex-1 overflow-auto rounded bg-white p-4">
                        @RenderBody()
                    </main>
                </div>
                <footer class="flex items-center h-8 px-4">
                    <p class="text-sm">
                        &copy; 2024 <a class="text-vellink" href="https://www.velsol.com/" target="_blank">Velocitor Solutions</a>
                    </p>
                </footer>
            </div>
        </div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

Views/Shared/_SidebarPartial.cshtml
<aside class="sidebar transition-all duration-300 ease-in-out overflow-hidden bg-velgray" id="sidebar">
    <div class="flex justify-center items-center h-[4.125rem] bg-velblue">
        <img src="~/images/VTrack-Logo-Small.png" alt="Velocitor Solutions" class="" />
    </div>
    <div class="flex flex-col items-center">
        @await Component.InvokeAsync("SidebarItem", new {
            linkText = "Dashboard",
            iconClass = "fa-solid fa-gauge-high ",
            aspArea = "", aspController = "Home", aspAction = "Index"
        })
        @await Component.InvokeAsync("SidebarItem", new {
            linkText = "Fleet",
            iconClass = "fa-solid fa-location-dot",
            aspArea = "", aspController = "Home", aspAction = "Privacy"
        })
        @await Component.InvokeAsync("SidebarItem", new {
            linkText = "Drivers",
            iconClass = "fa-solid fa-user ",
            aspArea = "", aspController = "Home", aspAction = "Privacy"
        })
    </div>
</aside>